image: node:20

pipelines:
  default:
    - step:
        name: Gen2E CI
        caches:
          - node
        script:
          - npm ci --include=optional
          - npm run build
          - npm test