import { type Gen2ELogger, makeLogger } from "@rhighs/gen2e-logger";
import { createGateway, gateway, type LanguageModel } from "ai";
import { Gen2ELLMGenericError } from "./errors";
import {
  isGatewayModel,
  isModelSupported,
  isOpenAIModel,
  isProviderModel,
  modelId,
  modelKey,
} from "./models";
import { Gen2EOpenAIRunner } from "./runner/openai";
import { Gen2EVercelRunner } from "./runner/vercel";
import { sanitizeCodeOutput, validateJSCode, validateJSONString } from "./sanity";
import { makeTool, makeTracedTool } from "./tools";
import { makeFormatTool } from "./tools/ensure-format";
import {
  type Gen2ELLMAgent,
  type Gen2ELLMAgentBuilder,
  type Gen2ELLMAgentBuilderOptions,
  type Gen2ELLMAgentModel,
  Gen2ELLMAgentOpenAIModels,
  type Gen2ELLMAgentResult,
  type Gen2ELLMAgentRunner,
  type Gen2ELLMAgentRunnerInit,
  type Gen2ELLMAgentTool,
  type Gen2ELLMAgentUsageStats,
  type Gen2ELLMCodeGenAgent,
  type Gen2ELLMCodeGenAgentTask,
} from "./types";

const createCodeGenTools = (lang: string) => {
  const tools = [
    makeTracedTool(
      makeFormatTool(({ code }) => {
        if (
          code.startsWith("```") ||
          code.startsWith("\\`\\`\\`") ||
          code.endsWith("```") ||
          code.endsWith("\\`\\`\\`")
        ) {
          return {
            success: false,
            reason:
              "Invalid format, do not use markdown. Code should be formatted as plain string.",
          };
        }

        return {
          success: true,
        };
      }),
    ),
  ];

  if (lang === "javascript" || lang === "typescript") {
    tools.push(
      makeTracedTool(
        makeTool(({ code }) => {
          return validateJSCode(code);
        }),
      ),
    );
  }

  if (lang === "json") {
    tools.push(
      makeTracedTool(
        makeTool(({ code }) => {
          return validateJSONString(code);
        }),
      ),
    );
  }

  return tools;
};

const makePrompt = (
  message: string,
  codeContext: string | undefined,
  attempts: string | undefined,
  errors: string | undefined,
) =>
  `\
This is your task: ${message}

${
  attempts?.length
    ? `\
These are past attemps, try something different:
${attempts}
  `
    : ""
}

${
  errors?.length
    ? `\
These are errors generated by the previous attempts:
${errors}
  `
    : ""
}

${
  codeContext?.length
    ? `\
This is the code context relevant for the code you'll generate:
\`\`\`
${codeContext}
\`\`\`

Make sure the expression you generate does no include variable names that clash with the code above.
Make sure to only return the missing statement or exactly what asked by your task.
Never give back the full context, only the new part.`
    : ""
}`;

const defaultAgentLogger = makeLogger("GEN2E-LLM");

/**
 * Resolve a `provider/model` gateway id against the Vercel AI Gateway. When an
 * explicit key is given a dedicated provider is created, otherwise the default
 * provider reads AI_GATEWAY_API_KEY from the environment.
 */
const resolveGatewayModel = (id: string, options?: Gen2ELLMAgentBuilderOptions): LanguageModel => {
  const provider = options?.gatewayApiKey
    ? createGateway({ apiKey: options.gatewayApiKey })
    : gateway;
  return provider(id);
};

const buildRunner = (
  model: Gen2ELLMAgentModel,
  options: Gen2ELLMAgentBuilderOptions | undefined,
  logger: Gen2ELogger,
  debug: boolean,
): Gen2ELLMAgentRunner => {
  const runnerOptions = {
    debug,
    logger,
    maxSteps: options?.maxSteps,
    temperature: options?.temperature,
  };

  if (isProviderModel(model)) {
    return new Gen2EVercelRunner({
      model: model as LanguageModel,
      ...runnerOptions,
    });
  }

  if (typeof model === "string" && isGatewayModel(model)) {
    return new Gen2EVercelRunner({
      model: resolveGatewayModel(model, options),
      ...runnerOptions,
    });
  }

  if (typeof model === "string" && (isOpenAIModel(model) || model in Gen2ELLMAgentOpenAIModels)) {
    const apiKey = options?.openaiApiKey ?? process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Gen2ELLMGenericError("openai model supplied but no openai api key was found");
    }
    return new Gen2EOpenAIRunner({
      apiKey,
      model,
      debug,
      logger,
      baseURL: options?.baseURL,
    });
  }

  throw new Gen2ELLMGenericError(`unsupported model type ${String(model)}`);
};

export const createCodeGenAgent: Gen2ELLMAgentBuilder<Gen2ELLMCodeGenAgent> = (
  systemMessage: string,
  model: Gen2ELLMAgentModel,
  options?: Gen2ELLMAgentBuilderOptions,
  logger?: Gen2ELogger,
  tools?: Gen2ELLMAgentTool<{ code?: string; [key: string]: any }>[],
  defaultLang: string = "javascript",
): Gen2ELLMAgent<Gen2ELLMCodeGenAgentTask, string> => {
  const isDebug = options?.debug ?? false;
  const _logger = defaultAgentLogger;
  if (logger) {
    _logger.config(logger);
  }

  const defaultTools = createCodeGenTools(defaultLang);
  let allTools = [...defaultTools];
  if (tools) {
    allTools = [...allTools, ...tools.map((tool) => makeTracedTool(tool))];
  }

  if (!isModelSupported(model)) {
    throw new Gen2ELLMGenericError(`unsupported model type ${String(model)}`);
  }

  const runners = new Map<string, { runner: Gen2ELLMAgentRunner; model: Gen2ELLMAgentModel }>();
  const getRunner = (override?: Gen2ELLMAgentModel) => {
    const target = override ?? model;
    const key = modelKey(target);
    let entry = runners.get(key);
    if (!entry) {
      entry = {
        runner: buildRunner(target, options, _logger, isDebug),
        model: target,
      };
      runners.set(key, entry);
    }
    return entry;
  };

  const totalToolCalls = () => allTools.reduce((acc, tool) => acc + tool.callCount(), 0);

  // Resolve the initial runner eagerly so misconfiguration surfaces when the
  // agent is created, not on the first generation request.
  getRunner();

  return async (task, hooks): Promise<Gen2ELLMAgentResult<string>> => {
    let entry: {
      runner: Gen2ELLMAgentRunner;
      model: Gen2ELLMAgentModel;
    };
    try {
      entry = getRunner(task.options?.model);
    } catch (err) {
      return {
        type: "error",
        errorMessage: `LLM call error ${err}`,
      };
    }

    const toolCallsBefore = totalToolCalls();
    const taskPrompt = makePrompt(
      task.task,
      task.codeContext,
      task.previousAttempts,
      task.previousErrors,
    );

    let expression = "";
    try {
      const runOpts: Gen2ELLMAgentRunnerInit = {
        taskPrompt,
        systemMessage,
        tools: allTools,
      };
      if (task.options?.model) {
        runOpts.options = {
          model: task.options?.model,
        };
      }

      if (task.images) {
        if (isDebug) {
          _logger.debug("using runner with image on model", modelId(entry.model));
        }
        runOpts.images = task.images;
      }

      const result = await entry.runner.run(runOpts, hooks);
      if (result.type === "error") {
        return {
          type: "error",
          errorMessage: `llm runner failed with reason ${result.reason}`,
        };
      }
      expression = result.result;

      const usage = await entry.runner.getUsage();
      const usageStats: Gen2ELLMAgentUsageStats = {
        model: modelId(entry.model),
        promptVersion: options?.promptVersion,
        task: {
          prompt: taskPrompt,
          output: expression ?? "",
          noToolCalls: totalToolCalls() - toolCallsBefore,
        },
        completionTokens: usage.completionTokens,
        promptTokens: usage.promptTokens,
        totalTokens: usage.totalTokens,
      };

      if (!expression) {
        return {
          type: "error",
          errorMessage: `LLM did not generate valid content as final content, got null or empty response = ${expression}`,
        };
      }

      if (hooks?.onUsage) {
        await hooks.onUsage(usageStats);
      }
    } catch (err) {
      return {
        type: "error",
        errorMessage: `LLM call error ${err}`,
      };
    }

    const sanitizedExpr = sanitizeCodeOutput(expression);
    if (defaultLang === "javascript" || defaultLang === "typescript") {
      if (!validateJSCode(sanitizedExpr)) {
        return {
          type: "error",
          errorMessage: `llm runner failed generation a valid javascript expression, got ${sanitizedExpr}`,
        };
      }
    }

    if (isDebug) {
      _logger.debug("non-sanitized expression ", { expression });
      _logger.debug("sanitized expression result ", {
        expression: sanitizedExpr,
      });
    }

    return {
      type: "success",
      result: sanitizedExpr,
    };
  };
};
