import { type Gen2ELogger, makeLogger } from "@rhighs/gen2e-logger";
import { Gen2ELLMGenericError } from "./errors";
import { isModelSupported, modelId } from "./models";
import { Gen2EOpenAIRunner } from "./runner/openai";
import { sanitizeCodeOutput, validateJSCode, validateJSONString } from "./sanity";
import { makeTool, makeTracedTool } from "./tools";
import { makeFormatTool } from "./tools/ensure-format";
import type {
  Gen2ELLMAgent,
  Gen2ELLMAgentBuilder,
  Gen2ELLMAgentBuilderOptions,
  Gen2ELLMAgentModel,
  Gen2ELLMAgentResult,
  Gen2ELLMAgentRunner,
  Gen2ELLMAgentRunnerInit,
  Gen2ELLMAgentTool,
  Gen2ELLMAgentUsageStats,
  Gen2ELLMCodeGenAgent,
  Gen2ELLMCodeGenAgentTask,
} from "./types";

const createCodeGenTools = (lang: string) => {
  const tools = [
    makeTracedTool(
      makeFormatTool(({ code }) => {
        if (
          code.startsWith("```") ||
          code.startsWith("\\`\\`\\`") ||
          code.endsWith("```") ||
          code.endsWith("\\`\\`\\`")
        ) {
          return {
            success: false,
            reason:
              "Invalid format, do not use markdown. Code should be formatted as plain string.",
          };
        }

        return {
          success: true,
        };
      }),
    ),
  ];

  if (lang === "javascript" || lang === "typescript") {
    tools.push(
      makeTracedTool(
        makeTool(({ code }) => {
          return validateJSCode(code);
        }),
      ),
    );
  }

  if (lang === "json") {
    tools.push(
      makeTracedTool(
        makeTool(({ code }) => {
          return validateJSONString(code);
        }),
      ),
    );
  }

  return tools;
};

const makePrompt = (
  message: string,
  codeContext: string | undefined,
  attempts: string | undefined,
  errors: string | undefined,
) =>
  `\
This is your task: ${message}

${
  attempts?.length
    ? `\
These are past attemps, try something different:
${attempts}
  `
    : ""
}

${
  errors?.length
    ? `\
These are errors generated by the previous attempts:
${errors}
  `
    : ""
}

${
  codeContext?.length
    ? `\
This is the code context relevant for the code you'll generate:
\`\`\`
${codeContext}
\`\`\`

Make sure the expression you generate does no include variable names that clash with the code above.
Make sure to only return the missing statement or exactly what asked by your task.
Never give back the full context, only the new part.`
    : ""
}`;

const defaultAgentLogger = makeLogger("GEN2E-LLM");

/**
 * Build the runner for a model id. Every model is served through the OpenAI
 * SDK against the configured OpenAI-compatible endpoint (base URL plus API
 * key), so a single runner covers OpenAI and any compatible endpoint.
 */
const buildRunner = (
  model: Gen2ELLMAgentModel,
  options: Gen2ELLMAgentBuilderOptions | undefined,
  logger: Gen2ELogger,
  debug: boolean,
): Gen2ELLMAgentRunner => {
  const apiKey = options?.openaiApiKey ?? process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Gen2ELLMGenericError(
      "no API key found for the OpenAI-compatible endpoint (set openaiApiKey or OPENAI_API_KEY)",
    );
  }
  return new Gen2EOpenAIRunner({
    apiKey,
    model,
    debug,
    logger,
    baseURL: options?.baseURL,
  });
};

export const createCodeGenAgent: Gen2ELLMAgentBuilder<Gen2ELLMCodeGenAgent> = (
  systemMessage: string,
  model: Gen2ELLMAgentModel,
  options?: Gen2ELLMAgentBuilderOptions,
  logger?: Gen2ELogger,
  tools?: Gen2ELLMAgentTool<{ code?: string; [key: string]: any }>[],
  defaultLang: string = "javascript",
): Gen2ELLMAgent<Gen2ELLMCodeGenAgentTask, string> => {
  const isDebug = options?.debug ?? false;
  const _logger = defaultAgentLogger;
  if (logger) {
    _logger.config(logger);
  }

  const defaultTools = createCodeGenTools(defaultLang);
  let allTools = [...defaultTools];
  if (tools) {
    allTools = [...allTools, ...tools.map((tool) => makeTracedTool(tool))];
  }

  if (!isModelSupported(model)) {
    throw new Gen2ELLMGenericError(`unsupported model type ${String(model)}`);
  }

  const runners = new Map<string, { runner: Gen2ELLMAgentRunner; model: Gen2ELLMAgentModel }>();
  const getRunner = (override?: Gen2ELLMAgentModel) => {
    const target = override ?? model;
    const key = modelId(target);
    let entry = runners.get(key);
    if (!entry) {
      entry = {
        runner: buildRunner(target, options, _logger, isDebug),
        model: target,
      };
      runners.set(key, entry);
    }
    return entry;
  };

  const totalToolCalls = () => allTools.reduce((acc, tool) => acc + tool.callCount(), 0);

  // Resolve the initial runner eagerly so misconfiguration surfaces when the
  // agent is created, not on the first generation request.
  getRunner();

  return async (task, hooks): Promise<Gen2ELLMAgentResult<string>> => {
    let entry: {
      runner: Gen2ELLMAgentRunner;
      model: Gen2ELLMAgentModel;
    };
    try {
      entry = getRunner(task.options?.model);
    } catch (err) {
      return {
        type: "error",
        errorMessage: `LLM call error ${err}`,
      };
    }

    const toolCallsBefore = totalToolCalls();
    const taskPrompt = makePrompt(
      task.task,
      task.codeContext,
      task.previousAttempts,
      task.previousErrors,
    );

    let expression = "";
    try {
      const runOpts: Gen2ELLMAgentRunnerInit = {
        taskPrompt,
        systemMessage,
        tools: allTools,
      };
      if (task.options?.model) {
        runOpts.options = {
          model: task.options?.model,
        };
      }

      if (task.images) {
        if (isDebug) {
          _logger.debug("using runner with image on model", modelId(entry.model));
        }
        runOpts.images = task.images;
      }

      const result = await entry.runner.run(runOpts, hooks);
      if (result.type === "error") {
        return {
          type: "error",
          errorMessage: `llm runner failed with reason ${result.reason}`,
        };
      }
      expression = result.result;

      const usage = await entry.runner.getUsage();
      const usageStats: Gen2ELLMAgentUsageStats = {
        model: modelId(entry.model),
        promptVersion: options?.promptVersion,
        task: {
          prompt: taskPrompt,
          output: expression ?? "",
          noToolCalls: totalToolCalls() - toolCallsBefore,
        },
        completionTokens: usage.completionTokens,
        promptTokens: usage.promptTokens,
        totalTokens: usage.totalTokens,
      };

      if (!expression) {
        return {
          type: "error",
          errorMessage: `LLM did not generate valid content as final content, got null or empty response = ${expression}`,
        };
      }

      if (hooks?.onUsage) {
        await hooks.onUsage(usageStats);
      }
    } catch (err) {
      return {
        type: "error",
        errorMessage: `LLM call error ${err}`,
      };
    }

    const sanitizedExpr = sanitizeCodeOutput(expression);
    if (defaultLang === "javascript" || defaultLang === "typescript") {
      if (!validateJSCode(sanitizedExpr)) {
        return {
          type: "error",
          errorMessage: `llm runner failed generation a valid javascript expression, got ${sanitizedExpr}`,
        };
      }
    }

    if (isDebug) {
      _logger.debug("non-sanitized expression ", { expression });
      _logger.debug("sanitized expression result ", {
        expression: sanitizedExpr,
      });
    }

    return {
      type: "success",
      result: sanitizedExpr,
    };
  };
};
